# Base Node.js image
FROM node:20-slim

# Install dependencies for Oracle Instant Client
RUN apt-get update && apt-get install -y \
    unzip libaio1 wget \
    && rm -rf /var/lib/apt/lists/*

# Install Oracle Instant Client
WORKDIR /opt/oracle
RUN wget https://www.oracle.com/webapps/redirect/signon?nexturl=https://download.oracle.com/otn/linux/instantclient/122010/instantclient-basic-linux.x64-12.2.0.1.0.zip \
    && unzip instantclient-basiclite-linux.x64-23.9.zip \
    && rm instantclient-basiclite-linux.x64-23.9.zip

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_23_9

# Set up app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

CMD ["node", "index.js"]